language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
before_install:
  - git config --global user.email "hashdist@h.com";
    git config --global user.name "Hashdist"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
      pip install argparse unittest2;
    fi
script:
  - nosetests -v -s
branches:
  only:
    - master
notifications:
  email: false
